In [75]:
pwd

'C:\\Users\\Taha'

In [76]:
cd C:/users/Taha/Pyton codes/Comp Method


C:\users\Taha\Pyton codes\Comp Method


In [77]:
pwd

'C:\\users\\Taha\\Pyton codes\\Comp Method'

In [8]:
y = 100 < 10
y, type(y)

(False, bool)

In [78]:
x = 50 > 2
x, type(x)

(True, bool)

In [81]:
a, b = 1, 2
c, d = 2.5 ,10.00

In [82]:
type(d), type(a), type(c)

(float, int, float)

In [84]:
x = complex(1,2)
x

y = complex(2,5)
y

(2+5j)

In [104]:
a = [1,2,3,4,5]
a[1:4]


[2, 3, 4]

In [107]:
a[0] = 'a new number'
a

['a new number', 2, 3, 4, 5]

In [108]:
a[0]

'a new number'

In [109]:
b = [-1,-2,-3]
b

[-1, -2, -3]

In [110]:
a + b

['a new number', 2, 3, 4, 5, -1, -2, -3]

In [111]:
aa = [1]
q = aa + a + b
q

[1, 'a new number', 2, 3, 4, 5, -1, -2, -3]

In [112]:
x = 'a', 'b'
x, type(x)

(('a', 'b'), tuple)

In [114]:
x[0] = 'k'

TypeError: 'tuple' object does not support item assignment

In [117]:
dic ={'name':'Carole', 'height':6, 'age':33}
dic, type(dic)

SyntaxError: invalid syntax (<ipython-input-117-db18d19005dd>, line 1)

In [116]:
dic['name'], dic['height']

('Carole', 6)

In [120]:
set1 = {'a', 'b', 'c'}
set2 = {'b', 'c'}
set2.issubset(set1), set1.intersection(set2)

(True, {'b', 'c'})

In [121]:
names = set(('ali', 'james', 'bob', 'ali'))
names, type(names)

({'ali', 'bob', 'james'}, set)

In [122]:
x_val = [1, 2, 3]
for x in x_val:
    print(x**2)

1
4
9


In [130]:
y = [3,1,5]
for x in y:
    print(x**(1/2))

1.7320508075688772
1.0
2.23606797749979


In [132]:
countries = ('Japan', 'Korea', 'China')
cities = ('Tokyo', 'Seoul', 'Beijing')
for country, city in zip(countries, cities):
    print(f'The capital of {country} is {city}')

The capital of Japan is Tokyo
The capital of Korea is Seoul
The capital of China is Beijing


In [133]:
list1 = ['one', 'two', 'three']
for idx, digit in enumerate(list1):
    print(f'{digit} = {idx+1}')

one = 1
two = 2
three = 3


In [136]:
def square_func(x):
    return x ** 2
square_func(3)

9

In [135]:
square_func(4)

16

In [138]:
def sum_square_func(x, y): #defining a function
    return x ** 2 + y ** 2

sum_square_func_one_line = lambda x, y: x ** 2 + y ** 2 #defining a lambda function

sum_square_func_one_line(1,2), sum_square_func(1,2)

(5, 5)

In [149]:
x = complex(1,2)
x

(1+2j)

In [150]:
type(x)

complex

In [151]:
x.imag

2.0

In [152]:
x.__class__

complex

In [154]:
x = [1, 2, 3]
x.append(4)
x

[1, 2, 3, 4]

In [157]:
s = 'This is a string'
s_new = s.upper()
s_new

'THIS IS A STRING'

In [160]:
import numpy as np
import pandas as pd

In [159]:
np.version.version

'1.19.2'

In [168]:
import numpy as np
A = np.zeros((3,5))
A

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [169]:
A.__class__

numpy.ndarray

In [170]:
A.shape

(3, 5)

In [174]:
np.linspace(2,8,10)

array([2.        , 2.66666667, 3.33333333, 4.        , 4.66666667,
       5.33333333, 6.        , 6.66666667, 7.33333333, 8.        ])

In [176]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [60]:
my_array = np.array([[1,2,3],[4,5,6]],dtype=int)
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [181]:
my_array = np.array([[1,2,3],[4,5,6]])
my_array[1,2]

6

In [179]:
my_array[0,:]

array([1, 2, 3])

In [180]:
idx = (1,2)
my_array[idx]

6

In [183]:
max(my_array[:,2])

6

In [186]:
my_array.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [187]:
my_array = np.array([[1,2],[4,9]])
my_array


array([[1, 2],
       [4, 9]])

In [188]:
np.linalg.inv(my_array)

array([[ 9., -2.],
       [-4.,  1.]])

In [201]:

from numpy.random import default_rng
rng = default_rng(5)
import numpy as np
n = 10
x = rng.uniform(low=0.0,high=10.0,size=n)
x_mean = np.mean(x)
x_var = np.var(x)

print("the random numebrs are",x)
print("the mean is",x_mean)
print("the variance is",x_var)

the random numebrs are [8.05002924 8.0794079  5.15325561 2.8580138  0.53930702 3.83368881
 4.08473205 0.45275194 0.48757711 9.99176115]
the mean is 4.3530524628940155
the variance is 10.726449606265543


In [202]:
from numpy.random import default_rng
rng = default_rng(5)

mu, sigma = 5,10
n = 5
x = rng.normal(mu,sigma,n)
x_mean = np.mean(x)
x_var = np.var(x)
print("the random numebrs are",x)
print("the mean is",x_mean)
print("the variance is",x_var)

the random numebrs are [-3.01931425 -8.24358996  2.51638378  9.20445238 16.36046532]
the mean is 3.363679455156647
the variance is 75.8440586271978
