In [15]:
import numpy as np
import pandas as pd

In [16]:
pwd

'/Users/sagawithme/Documents/GitHub/selfstudy/Ex'

In [17]:
y = 1<10
y,type(y)

(True, bool)

In [18]:
a,b = 1,2
c,d=2.5,100.22
type(d),type(c),type(a),type(b)

(float, float, int, int)

In [19]:
# 复数




In [20]:
A = np.zeros((5,2))
A

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [21]:
A.__class__

numpy.ndarray

In [22]:
np.linspace(2,8,10)

array([2.        , 2.66666667, 3.33333333, 4.        , 4.66666667,
       5.33333333, 6.        , 6.66666667, 7.33333333, 8.        ])

In [23]:
B = np.array([[1,2,3],[4,5,6]])
B[0,2]

3

In [24]:
C = np.array([[1,2],[4,9]])
np.linalg.inv(C)

array([[ 9., -2.],
       [-4.,  1.]])

In [25]:
from numpy.random import default_rng
rng= default_rng(9)
import numpy as np

x = rng.uniform(low=0,high=10,size=5)
x_mean = np.mean(x)
x_var = np.var(x)

In [26]:
x,x_mean,x_var

(array([8.70249204, 2.86817209, 6.0314815 , 7.77534083, 7.1607463 ]),
 6.507646551265891,
 4.064688456084514)

In [27]:
rng

Generator(PCG64) at 0x7F8646B249E0