In [19]:
import numpy as np
import pandas as pd

In [20]:
A = np.zeros((5,2))
A

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [21]:
A.__class__

numpy.ndarray

In [22]:
np.linspace(2,8,10)

array([2.        , 2.66666667, 3.33333333, 4.        , 4.66666667,
       5.33333333, 6.        , 6.66666667, 7.33333333, 8.        ])

In [23]:
B = np.array([[1,2,3],[4,5,6]])
B[0,2]

3

In [24]:
C = np.array([[1,2],[4,9]])
np.linalg.inv(C)

array([[ 9., -2.],
       [-4.,  1.]])

In [25]:
from numpy.random import default_rng
rng= default_rng(9)
import numpy as np

x = rng.uniform(low=0,high=10,size=5)
x_mean = np.mean(x)
x_var = np.var(x)

In [26]:
x,x_mean,x_var

(array([8.70249204, 2.86817209, 6.0314815 , 7.77534083, 7.1607463 ]),
 6.507646551265891,
 4.064688456084514)

In [27]:
x = complex(1,2)
x

(1+2j)

In [28]:
y = complex(2,5)
y

(2+5j)

In [29]:
a= [1,2,3,4,5]
a[1:4]

[2, 3, 4]

In [30]:
a[0]='new'
a

['new', 2, 3, 4, 5]

In [31]:
b = [-1,-2,-3]
b

[-1, -2, -3]

In [32]:
a + b

['new', 2, 3, 4, 5, -1, -2, -3]

In [33]:
aa = [1]
q = aa + a + b
q

[1, 'new', 2, 3, 4, 5, -1, -2, -3]

In [34]:
x = 'a','b'
x,type(x)

(('a', 'b'), tuple)

In [35]:
x[0] = 'k'

TypeError: 'tuple' object does not support item assignment

In [ ]:
dic ={'name':'Carole', 'height':6, 'age':33}
dic, type(dic)

In [21]:
dic ={'name':'carole','height':6,'age':'33'}
dic,type(dic)

({'name': 'carole', 'height': 6, 'age': '33'}, dict)

In [22]:
dic['name']

'carole'

In [24]:
set1 = {'a', 'b', 'c'}
set2 = {'b', 'c'}
set2.issubset(set1)

True

In [26]:
names = set(('ali','james','bob','ali'))
names,type(names)

({'ali', 'bob', 'james'}, set)

In [27]:
x_val =[1,2,3]
for x in x_val:
    print(x**2)

1
4
9


In [31]:
y = [3,1,5]
for a in y:
    print(a**(1/2))

1.7320508075688772
1.0
2.23606797749979


In [ ]:
# coooooool zip

In [18]:
countries = ('Janpan',"korea","China")
cities =('Tokyo',"seoul",'Beijing')
for country,city in zip(countries,cities):
    print(f'the capital of {country} is {city}')

the capital of Janpan is Tokyo
the capital of korea is seoul
the capital of China is Beijing


In [19]:
# coooooool enumerate

In [4]:
list1 =['one','two','three']
for idx, digit in enumerate(list1):
    print(f'{digit} = {idx+1}')

one = 1
two = 2
three = 3


In [9]:
def square_func(x):
    return x**2
square_func(3)
square_func(4)

16

In [1]:
def sum_square_func(x,y):
    return x**2 + y**2

sum_square_func_one_line = lambda x,y:x**2 + y**2

sum_square_func(1,2),sum_square_func_one_line(1,2)

(5, 5)

In [2]:
x = complex(1,2)
x

(1+2j)

In [3]:
x.imag

2.0

In [5]:
x.__class__

complex

In [8]:
x = []
x.append(4)
x

[4]

In [11]:
s = 'This is a string'
s_new = s.upper()
s_new

'THIS IS A STRING'

In [12]:
import numpy as np
import pandas as pd

In [15]:
np.version.version

'1.20.2'

In [16]:
A = np.zeros((3,5))
A

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
A.__class__

numpy.ndarray

In [20]:
A.shape

(3, 5)

In [25]:
B = np.identity(10)
B

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [36]:
my_array = np.array([[1,2,3],[4,5,6]],dtype=int)

In [37]:
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
my_array[1,0]

4

In [31]:
my_array[1,2]

6

In [51]:
my_array = np.array([[1,2],[4,9]])
my_array

array([[ 9., -2.],
       [-4.,  1.]])

In [52]:
np.linalg.inv(my_array)

array([[ 9., -2.],
       [-4.,  1.]])

In [65]:
from numpy.random import default_rng
rng = default_rng(5)

mu, sigma = 5, 10
n = 5
x = rng.normal(mu,sigma,n)
x_mean = np.mean(x)
x_var = np.var(x)

print(f'the random numbers are {x},the mean is {x_mean},the variance is {x_var}')

the random numbers are [-3.01931425 -8.24358996  2.51638378  9.20445238 16.36046532],the mean is 3.363679455156647,the variance is 75.8440586271978
