In [1]:
import numpy as np
import pandas as pd

In [2]:
A = np.zeros((5,2))
A

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [3]:
A.__class__

numpy.ndarray

In [4]:
np.linspace(2,8,10)

array([2.        , 2.66666667, 3.33333333, 4.        , 4.66666667,
       5.33333333, 6.        , 6.66666667, 7.33333333, 8.        ])

In [5]:
B = np.array([[1,2,3],[4,5,6]])
B[0,2]

3

In [6]:
C = np.array([[1,2],[4,9]])
np.linalg.inv(C)

array([[ 9., -2.],
       [-4.,  1.]])

In [7]:
from numpy.random import default_rng
rng= default_rng(9)
import numpy as np

x = rng.uniform(low=0,high=10,size=5)
x_mean = np.mean(x)
x_var = np.var(x)

In [8]:
x,x_mean,x_var

(array([8.70249204, 2.86817209, 6.0314815 , 7.77534083, 7.1607463 ]),
 6.507646551265891,
 4.064688456084514)

In [10]:
x = complex(1,2)
x

(1+2j)

In [11]:
y = complex(2,5)
y

(2+5j)

In [12]:
a= [1,2,3,4,5]
a[1:4]

[2, 3, 4]

In [13]:
a[0]='new'
a

['new', 2, 3, 4, 5]

In [14]:
b = [-1,-2,-3]
b

[-1, -2, -3]

In [16]:
a + b

['new', 2, 3, 4, 5, -1, -2, -3]

In [18]:
aa = [1]
q = aa + a + b
q

[1, 'new', 2, 3, 4, 5, -1, -2, -3]

In [19]:
x = 'a','b'
x,type(x)

(('a', 'b'), tuple)

In [20]:
x[0] = 'k'

TypeError: 'tuple' object does not support item assignment

In [ ]:
dic ={'name':'Carole', 'height':6, 'age':33}
dic, type(dic)

In [21]:
dic ={'name':'carole','height':6,'age':'33'}
dic,type(dic)

({'name': 'carole', 'height': 6, 'age': '33'}, dict)

In [22]:
dic['name']

'carole'

In [24]:
set1 = {'a', 'b', 'c'}
set2 = {'b', 'c'}
set2.issubset(set1)

True

In [26]:
names = set(('ali','james','bob','ali'))
names,type(names)

({'ali', 'bob', 'james'}, set)

In [27]:
x_val =[1,2,3]
for x in x_val:
    print(x**2)

1
4
9


In [31]:
y = [3,1,5]
for a in y:
    print(a**(1/2))

1.7320508075688772
1.0
2.23606797749979


In [ ]:
# coooooool zip

In [30]:
countries = ('Janpan',"korea","China")
cities =('Tokyo',"seoul",'Beijing')
for country,city in zip(countries,cities):
    print(f'the capital of {country} is {city}')

the capital of Janpan is Tokyo
the capital of korea is seoul
the capital of China is Beijing


In [4]:
list1 =['one','two','three']
for idx, digit in enumerate(list1):
    print(f'{digit} = {idx+1}')

one = 1
two = 2
three = 3


In [9]:
def square_func(x):
    return x**2
square_func(3)
square_func(4)

16

In [9]:
rng

Generator(PCG64) at 0x7F8548BF3C80