# Creating arrays

In [1]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.zeros((3, 4)) #double bracket

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## Some vocabulary

* In NumPy, each dimension is called an **axis**.
* The number of axes is called the **rank**.
    * For example, the above 3x4 matrix is an array of rank 2 (it is 2-dimensional).
    * The first axis has length 3, the second has length 4.
* An array's list of axis lengths is called the **shape** of the array.
    * For example, the above matrix's shape is `(3, 4)`.
    * The rank is equal to the shape's length.
* The **size** of an array is the total number of elements, which is the product of all axis lengths (eg. 3*4=12)

In [8]:
a= np.zeros((3, 4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
a.shape

(3, 4)

In [10]:
a.ndim

2

In [11]:
a.size

12

## N-dimensional arrays
You can also create an N-dimensional array of arbitrary rank. For example, here's a 3D array (rank=3), with shape `(2,3,4)`:

In [14]:
b = np.zeros((2,3,4))
b

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [15]:
type(b)

numpy.ndarray

In [16]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

## np.full

In [19]:
np.full((2,3,4), np.exp(1))

array([[[2.71828183, 2.71828183, 2.71828183, 2.71828183],
        [2.71828183, 2.71828183, 2.71828183, 2.71828183],
        [2.71828183, 2.71828183, 2.71828183, 2.71828183]],

       [[2.71828183, 2.71828183, 2.71828183, 2.71828183],
        [2.71828183, 2.71828183, 2.71828183, 2.71828183],
        [2.71828183, 2.71828183, 2.71828183, 2.71828183]]])

## `np.empty`
An uninitialized 2x3 array (its content is not predictable, as it is whatever is in memory at that point):

In [21]:
np.empty((2,3))

array([[-1.28822975e-231, -2.32035885e+077,  1.48219694e-323],
       [ 0.00000000e+000,  0.00000000e+000,  4.17201348e-309]])

## `np.array`  (whatch here find" `````  "  )

In [23]:
np.array([[1, 2, 3, 4],[10, 20, 30, 40]])

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

In [24]:
np.arange(1,5)

array([1, 2, 3, 4])

In [28]:
np.arange(1000,10000,1000) #useful

array([1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000])

In [29]:
#compare
np.linspace(1000,10000,10)

array([ 1000.,  2000.,  3000.,  4000.,  5000.,  6000.,  7000.,  8000.,
        9000., 10000.])

In [27]:
print(np.arange(0, 5/3, 1/3)) # depending on floating point errors, the max value is 4/3 or 5/3.
print(np.arange(0, 5/3, 0.333333333))
print(np.arange(0, 5/3, 0.333333334))


[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667]
[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667]
[0.         0.33333333 0.66666667 1.         1.33333334]


In [33]:
np.linspace(10,1000,30)

array([  10.        ,   44.13793103,   78.27586207,  112.4137931 ,
        146.55172414,  180.68965517,  214.82758621,  248.96551724,
        283.10344828,  317.24137931,  351.37931034,  385.51724138,
        419.65517241,  453.79310345,  487.93103448,  522.06896552,
        556.20689655,  590.34482759,  624.48275862,  658.62068966,
        692.75862069,  726.89655172,  761.03448276,  795.17241379,
        829.31034483,  863.44827586,  897.5862069 ,  931.72413793,
        965.86206897, 1000.        ])

In [35]:
np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

## `np.rand` and `np.randn`
A number of functions are available in NumPy's `random` module to create `ndarray`s initialized with random values.
For example, here is a 3x4 matrix initialized with random floats between 0 and 1 (uniform distribution):